### PR TITLE
[flaky] Fix flaky tests caused by port binding

### LINKED ISSUE #109: [flaky-test] TestCommitterCMD race condition
Running the CI I ran into this race condition causing 3 tests to fail in `TestCommitterCMD`

### _This did not reproduce on 2nd or 3rd run attempts_ 
_Also locally could not recreate this scenario_

See: [CI Build b428b](https://github.com/hyperledger/fabric-x-committer/pull/103/commits/a9067e9d6e6c50c686e50a8391145df2e08b428b)

Image

Log segment:
```
📦 github.com/hyperledger/fabric-x-committer/service/vc/dbtest
🚧 TestContainerStartAndQuery (0s)
✅ TestDefaultStartAndQuery (560ms)

📦 github.com/hyperledger/fabric-x-committer/cmd/committer
❌ TestCommitterCMD (10m6.25s)
  2025-08-06T09:43:02.727Z	INFO	connection/server_util.go:94	Listening on: tcp://localhost:46833
  2025-08-06T09:43:02.733Z	INFO	connection/server_util.go:94	Listening on: tcp://localhost:46683
  2025-08-06T09:43:02.733Z	INFO	connection/server_util.go:94	Listening on: tcp://localhost:40525
  2025-08-06T09:43:02.744Z	INFO	connection/server_util.go:94	Listening on: tcp://localhost:46415
      main_test.go:20: connection endpoints: [localhost:5433]
  2025-08-06T09:43:02.758Z	INFO	dbtest/connection.go:120	[localhost:5433] Connected to database
      main_test.go:20: connection nodes details: localhost:5433
      main_test.go:20: [TestCommitterCMD] db name: sc_test_5oa5nl4htxlsbibxbbvhr5x2uosoe2ndnrw47jsuh2x7d23tcvnq
  2025-08-06T09:43:02.933Z	INFO	connection/server_util.go:94	Listening on: tcp://localhost:40935
  2025-08-06T09:43:02.933Z	INFO	connection/client_util.go:140	Closing 1 connections.
✅ TestCommitterCMD/Coordinator (1s)
✅ TestCommitterCMD/Coordinator/start (500ms)
✅ TestCommitterCMD/Coordinator/start_with_endpoint (500ms)
✅ TestCommitterCMD/Query-Service (1s)
✅ TestCommitterCMD/Query-Service/start (500ms)
✅ TestCommitterCMD/Query-Service/start_with_endpoint (500ms)
✅ TestCommitterCMD/Sidecar (1s)
✅ TestCommitterCMD/Sidecar/start (500ms)
✅ TestCommitterCMD/Sidecar/start_with_endpoint (500ms)
✅ TestCommitterCMD/Validator-Committer (1.01s)
✅ TestCommitterCMD/Validator-Committer/start (500ms)
✅ TestCommitterCMD/Validator-Committer/start_with_endpoint (500ms)
❌ TestCommitterCMD/Verifier (10m0.5s)
❌ TestCommitterCMD/Verifier/start (10m0s)
      cobra_test_exports.go:117: Starting command
  2025-08-06T09:43:07.956Z	DEBUG	config/app_config.go:101	Decoded config: {"Logging":{"Enabled":true,"Level":"DEBUG","Caller":true,"Development":true,"Output":"/tmp/TestCommitterCMDVerifierstart2744461534/001/logger-output.txt","Name":"verifier"}}
  2025-08-06T09:43:07.956Z	DEBUG	verifier	config/app_config.go:101	Decoded config: {"Server":{"Endpoint":{"host":"localhost","port":40935},"Creds":null,"KeepAlive":null},"Monitoring":{"Server":{"Endpoint":{"host":"localhost"},"Creds":null,"KeepAlive":null}},"ParallelExecutor":{"Parallelism":40,"BatchSizeCutoff":50,"BatchTimeCutoff":10000000,"ChannelBufferSize":50}}
  2025-08-06T09:43:07.956Z	INFO	verifier	verifier/verifier_server.go:43	Initializing new verifier server
  2025-08-06T09:43:07.956Z	DEBUG	verifier	monitoring/provider.go:49	Creating prometheus server
  2025-08-06T09:43:07.957Z	INFO	verifier	connection/server_util.go:94	Listening on: tcp://localhost:34263
  2025-08-06T09:43:07.957Z	INFO	verifier	monitoring/provider.go:78	Prometheus serving on URL: http://127.0.0.1:34263/metrics
  2025-08-06T09:43:07.957Z	INFO	verifier	monitoring/provider.go:80	Prometheus stopped serving
  2025-08-06T09:43:07.957Z	INFO	verifier	connection/client_util.go:140	Closing 1 connections.
      cobra_test_exports.go:122: 
          	Error Trace:	/home/runner/work/fabric-x-committer/fabric-x-committer/cmd/config/cobra_test_exports.go:122
          	            				/opt/hostedtoolcache/go/1.24.3/x64/src/runtime/asm_amd64.s:1700
          	Error:      	Not equal: 
          	            	expected: <nil>(<nil>)
          	            	actual  : *withstack.withStack(&withstack.withStack{
          	            	    cause: &errutil.withPrefix{
          	            	        cause: &net.OpError{
          	            	            Op:     "listen",
          	            	            Net:    "tcp",
          	            	            Source: nil,
          	            	            Addr:   &net.TCPAddr{
          	            	                IP:   {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0x7f, 0x0, 0x0, 0x1},
          	            	                Port: 40935,
          	            	                Zone: "",
          	            	            },
          	            	            Err: &os.SyscallError{
          	            	                Syscall: "bind",
          	            	                Err:     syscall.Errno(0x62),
          	            	            },
          	            	        },
          	            	        prefix: "failed to listen",
          	            	    },
          	            	    stack: &withstack.stack{0xd4daf5, 0xd4dc05, 0xd4e228, 0xabecb0, 0x4844e1},
          	            	})
          	Test:       	TestCommitterCMD/Verifier/start
      cobra_test_exports.go:123: Command exited
      main_test.go:79: 
          	Error Trace:	/home/runner/work/fabric-x-committer/fabric-x-committer/cmd/config/cobra_test_exports.go:125
          	            				/home/runner/work/fabric-x-committer/fabric-x-committer/cmd/committer/main_test.go:79
          	Error:      	Condition never satisfied
          	Test:       	TestCommitterCMD/Verifier/start
      main_test.go:79: Stopping command, and waiting for finish
      main_test.go:79: Test finished with error
      main_test.go:79: STD OUT:
           Starting Verifier
          Verifier ended
          
      main_test.go:79: STD ERR:
           Error: failed to listen: listen tcp 127.0.0.1:40935: bind: address already in use
          
      main_test.go:79: LOG:
           2025-08-06T09:43:07.956Z	DEBUG	config/app_config.go:101	Decoded config: {"Logging":{"Enabled":true,"Level":"DEBUG","Caller":true,"Development":true,"Output":"/tmp/TestCommitterCMDVerifierstart2744461534/001/logger-output.txt","Name":"verifier"}}
          2025-08-06T09:43:07.956Z	DEBUG	verifier	config/app_config.go:101	Decoded config: {"Server":{"Endpoint":{"host":"localhost","port":40935},"Creds":null,"KeepAlive":null},"Monitoring":{"Server":{"Endpoint":{"host":"localhost"},"Creds":null,"KeepAlive":null}},"ParallelExecutor":{"Parallelism":40,"BatchSizeCutoff":50,"BatchTimeCutoff":10000000,"ChannelBufferSize":50}}
          2025-08-06T09:43:07.956Z	INFO	verifier	verifier/verifier_server.go:43	Initializing new verifier server
          2025-08-06T09:43:07.956Z	DEBUG	verifier	monitoring/provider.go:49	Creating prometheus server
          2025-08-06T09:43:07.957Z	INFO	verifier	connection/server_util.go:94	Listening on: tcp://localhost:34263
          2025-08-06T09:43:07.957Z	INFO	verifier	monitoring/provider.go:78	Prometheus serving on URL: http://127.0.0.1:34263/metrics
          2025-08-06T09:43:07.957Z	INFO	verifier	monitoring/provider.go:80	Prometheus stopped serving
          2025-08-06T09:43:07.957Z	INFO	verifier	connection/client_util.go:140	Closing 1 connections.
          
      main_test.go:79: Missing: Serving
      main_test.go:79: Missing: localhost:40935
      cobra_test_exports.go:107: Waiting for command to finish
      cobra_test_exports.go:110: Command finished
```

### LINKED ISSUE #137: [flaky-test] TestBroadcastDeliver
```
❌ TestBroadcastDeliver (10.12s)
      client_test.go:42: Instance count: 12; idCount: 3
  2025-09-17T07:53:34.580Z	INFO	connection/server_util.go:89	Listening on: tcp://localhost:36745
  2025-09-17T07:53:34.580Z	INFO	connection/server_util.go:89	Listening on: tcp://localhost:36787
  2025-09-17T07:53:34.580Z	INFO	connection/server_util.go:89	Listening on: tcp://localhost:35281
  2025-09-17T07:53:34.580Z	INFO	connection/server_util.go:89	Listening on: tcp://localhost:44117
  2025-09-17T07:53:34.580Z	INFO	connection/server_util.go:89	Listening on: tcp://localhost:36897
  2025-09-17T07:53:34.581Z	INFO	connection/server_util.go:89	Listening on: tcp://localhost:36031
  2025-09-17T07:53:34.581Z	INFO	connection/server_util.go:89	Listening on: tcp://localhost:43135
  2025-09-17T07:53:34.581Z	INFO	connection/server_util.go:89	Listening on: tcp://localhost:34885
  2025-09-17T07:53:34.581Z	INFO	connection/server_util.go:89	Listening on: tcp://localhost:44249
  2025-09-17T07:53:34.581Z	INFO	connection/server_util.go:89	Listening on: tcp://localhost:40727
  2025-09-17T07:53:34.581Z	INFO	connection/server_util.go:89	Listening on: tcp://localhost:41471
  2025-09-17T07:53:34.582Z	INFO	connection/server_util.go:89	Listening on: tcp://localhost:34293
      client_test.go:42: ENDPOINT [00] id=0,localhost:36745
      client_test.go:42: ENDPOINT [01] id=1,localhost:36787
      client_test.go:42: ENDPOINT [02] id=2,localhost:35281
      client_test.go:42: ENDPOINT [03] id=0,localhost:44117
      client_test.go:42: ENDPOINT [04] id=1,localhost:36897
      client_test.go:42: ENDPOINT [05] id=2,localhost:36031
      client_test.go:42: ENDPOINT [06] id=0,localhost:43135
      client_test.go:42: ENDPOINT [07] id=1,localhost:34885
      client_test.go:42: ENDPOINT [08] id=2,localhost:44249
      client_test.go:42: ENDPOINT [09] id=0,localhost:40727
      client_test.go:42: ENDPOINT [10] id=1,localhost:41471
      client_test.go:42: ENDPOINT [11] id=2,localhost:34293
  2025-09-17T07:53:34.582Z	INFO	ordererconn/conn_manager.go:196	Opening connections to 2 endpoints: [localhost:44117 localhost:36745].
  2025-09-17T07:53:34.582Z	INFO	ordererconn/conn_manager.go:196	Opening connections to 2 endpoints: [localhost:36897 localhost:36787].
  2025-09-17T07:53:34.582Z	INFO	ordererconn/conn_manager.go:196	Opening connections to 2 endpoints: [localhost:36031 localhost:35281].
  2025-09-17T07:53:34.582Z	INFO	ordererconn/conn_manager.go:196	Opening connections to 6 endpoints: [localhost:36897 localhost:35281 localhost:36031 localhost:44117 localhost:36787 localhost:36745].
      client_test.go:67: Read config block
  2025-09-17T07:53:34.582Z	WARN	deliver/client.go:70	deliver consensus type BFT is not supported; falling back to CFT
  2025-09-17T07:53:34.583Z	INFO	deliver/deliver_cft.go:88	Deliver connected to 127.0.0.1:44117
  2025-09-17T07:53:34.584Z	INFO	deliver/deliver_cft.go:135	Sending seek request from block 0 on channel mychannel.
  2025-09-17T07:53:34.584Z	INFO	deliver/deliver_cft.go:143	Seek request sent.
  2025-09-17T07:53:34.584Z	INFO	mock/orderer.go:180	Starting delivery with 127.0.0.1:47924 [0 -> 18446744073709551615]
      client_test.go:73: All good
  2025-09-17T07:53:34.585Z	INFO	ordererconn/conn_manager.go:196	Opening connections to 2 endpoints: [localhost:35281 localhost:36031].
  2025-09-17T07:53:34.585Z	INFO	ordererconn/conn_manager.go:196	Opening connections to 2 endpoints: [localhost:36745 localhost:44117].
  2025-09-17T07:53:34.585Z	INFO	ordererconn/conn_manager.go:196	Opening connections to 2 endpoints: [localhost:36787 localhost:36897].
  2025-09-17T07:53:34.585Z	INFO	ordererconn/conn_manager.go:196	Opening connections to 6 endpoints: [localhost:35281 localhost:36897 localhost:44117 localhost:36745 localhost:36787 localhost:36031].
  2025-09-17T07:53:34.586Z	INFO	mock/orderer.go:152	Starting broadcast with 127.0.0.1:47932
  2025-09-17T07:53:34.586Z	INFO	mock/orderer.go:152	Starting broadcast with 127.0.0.1:50578
  2025-09-17T07:53:34.587Z	INFO	connection/client_util.go:154	Closing 11 connections.
  2025-09-17T07:53:34.587Z	INFO	mock/orderer.go:152	Starting broadcast with 127.0.0.1:40768
  2025-09-17T07:53:34.587Z	INFO	mock/orderer.go:159	Finished broadcast with 127.0.0.1:40768
  2025-09-17T07:53:34.587Z	INFO	mock/orderer.go:159	Finished broadcast with 127.0.0.1:47932
  2025-09-17T07:53:34.587Z	INFO	mock/orderer.go:159	Finished broadcast with 127.0.0.1:50578
  2025-09-17T07:53:34.587Z	ERROR	connection/client_util.go:166	failed closing connections: rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
      client_test.go:78: One server down
      client_test.go:80: localhost:35281 is down
  2025-09-17T07:53:39.639Z	INFO	connection/client_util.go:154	Closing 1 connections.
  2025-09-17T07:53:39.639Z	INFO	ordererconn/conn_manager.go:196	Opening connections to 2 endpoints: [localhost:36745 localhost:44117].
  2025-09-17T07:53:39.639Z	INFO	ordererconn/conn_manager.go:196	Opening connections to 2 endpoints: [localhost:36897 localhost:36787].
  2025-09-17T07:53:39.639Z	INFO	ordererconn/conn_manager.go:196	Opening connections to 2 endpoints: [localhost:35281 localhost:36031].
  2025-09-17T07:53:39.640Z	INFO	ordererconn/conn_manager.go:196	Opening connections to 6 endpoints: [localhost:36745 localhost:36787 localhost:35281 localhost:36031 localhost:44117 localhost:36897].
  2025-09-17T07:53:39.641Z	INFO	mock/orderer.go:152	Starting broadcast with 127.0.0.1:40776
  2025-09-17T07:53:39.642Z	INFO	mock/orderer.go:152	Starting broadcast with 127.0.0.1:47934
  2025-09-17T07:53:39.642Z	INFO	connection/client_util.go:154	Closing 11 connections.
  2025-09-17T07:53:39.642Z	INFO	mock/orderer.go:152	Starting broadcast with 127.0.0.1:50584
  2025-09-17T07:53:39.643Z	INFO	mock/orderer.go:159	Finished broadcast with 127.0.0.1:47934
  2025-09-17T07:53:39.643Z	INFO	mock/orderer.go:159	Finished broadcast with 127.0.0.1:40776
  2025-09-17T07:53:39.643Z	INFO	mock/orderer.go:159	Finished broadcast with 127.0.0.1:50584
  2025-09-17T07:53:39.643Z	ERROR	connection/client_util.go:166	failed closing connections: rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
      client_test.go:85: Two servers down
      client_test.go:87: localhost:36031 is down
  2025-09-17T07:53:44.694Z	INFO	connection/client_util.go:154	Closing 1 connections.
  2025-09-17T07:53:44.694Z	INFO	ordererconn/conn_manager.go:196	Opening connections to 2 endpoints: [localhost:36031 localhost:35281].
  2025-09-17T07:53:44.694Z	INFO	ordererconn/conn_manager.go:196	Opening connections to 2 endpoints: [localhost:44117 localhost:36745].
  2025-09-17T07:53:44.694Z	INFO	ordererconn/conn_manager.go:196	Opening connections to 2 endpoints: [localhost:36897 localhost:36787].
  2025-09-17T07:53:44.695Z	INFO	ordererconn/conn_manager.go:196	Opening connections to 6 endpoints: [localhost:36787 localhost:36031 localhost:36745 localhost:36897 localhost:35281 localhost:44117].
  2025-09-17T07:53:44.696Z	INFO	mock/orderer.go:152	Starting broadcast with 127.0.0.1:58294
      client_test.go:88: 
          	Error Trace:	/home/runner/work/fabric-x-committer/fabric-x-committer/utils/deliver/client_test.go:162
          	            				/home/runner/work/fabric-x-committer/fabric-x-committer/utils/deliver/client_test.go:88
          	Error:      	An error is expected but got nil.
          	Test:       	TestBroadcastDeliver
  2025-09-17T07:53:44.697Z	INFO	connection/client_util.go:154	Closing 11 connections.
  2025-09-17T07:53:44.697Z	INFO	mock/orderer.go:152	Starting broadcast with 127.0.0.1:53688
  2025-09-17T07:53:44.698Z	INFO	mock/orderer.go:159	Finished broadcast with 127.0.0.1:58294
  2025-09-17T07:53:44.698Z	INFO	mock/orderer.go:159	Finished broadcast with 127.0.0.1:53688
  2025-09-17T07:53:44.698Z	ERROR	connection/client_util.go:166	failed closing connections: rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
  2025-09-17T07:53:44.698Z	INFO	connection/client_util.go:154	Closing 11 connections.
  2025-09-17T07:53:44.698Z	INFO	mock/orderer.go:196	Finished delivery with 127.0.0.1:47924
  2025-09-17T07:53:44.698Z	WARN	deliver/deliver_cft.go:64	Error receiving blocks: failed to receive block: rpc error: code = Canceled desc = context canceled
  2025-09-17T07:53:44.699Z	ERROR	connection/client_util.go:166	failed closing connections: rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
  rpc error: code = Canceled desc = grpc: the client connection is closing
```

### PR DESCRIPTION
**Pull request by liran-funaro**
#### Type of change

- Test update

#### Description

- [ServerConfig] Add retry mechanism when binding to a predefined port (`c.Listener()`).
- [TestBroadcastDeliver] Use the above retry mechanism to ensure the port is not used by other tests.

#### Related issues

- resolves #109 
- resolves #137

### CODE REVIEW

File: utils/connection/server_util.go [hunk 1]
```diff
@@ -70,11 +76,23 @@ func (c *ServerConfig) GrpcServer() (*grpc.Server, error) {
...
+// If the port is predefined, it will retry to bind to the port until successful or until the context ends.
+func (c *ServerConfig) Listener(ctx context.Context) (net.Listener, error) {
 	if c.preAllocatedListener != nil {
 		return c.preAllocatedListener, nil
 	}
-	listener, err := net.Listen(grpcProtocol, c.Endpoint.Address())
+
+	var err error
+	var listener net.Listener
+	if ctx == nil || c.Endpoint.Port == 0 {
```
Comment (cendhu) [inline utils/connection/server_util.go]: It is not intuitive that when the ctx is nil, retry till successful binding is not executed. I notice all callers to pass the ctx in the current code. Do we need this check?

File: utils/deliver/client_test.go [hunk 2]
```diff
@@ -77,20 +78,21 @@ func TestBroadcastDeliver(t *testing.T) {
 
 	t.Log("One server down")
 	servers[2].Servers[0].Stop()
-	waitUntilGrpcServerIsDown(ctx, t, &servers[2].Configs[0].Endpoint)
+	listener1 := holdPort(ctx, t, servers[2].Configs[0])
```
Comment (cendhu) [inline utils/deliver/client_test.go]: Earlier, we only checked whether the server was down or not. Now, we create another fake listener and explicitly close it. Can you please explain the reason as I might be missing the core issue?

File: utils/connection/server_util.go [hunk 3]
```diff
@@ -93,7 +111,7 @@ func (c *ServerConfig) Listener() (net.Listener, error) {
 // PreAllocateListener is used to allocate a port and bind to ahead of the server initialization.
 // It stores the listener object internally to be reused on subsequent calls to Listener().
 func (c *ServerConfig) PreAllocateListener() (net.Listener, error) {
-	listener, err := c.Listener()
+	listener, err := c.Listener(context.Background())
```
[the remark this answers is not in the document]
Comment (liran-funaro) [reply utils/connection/server_util.go]: No. PreallocateListener should only be used with `port=0`. If such attempt fails, there is no reason to retry.

**Review by cendhu — APPROVED** [review]
LGTM.
