### PR TITLE
[loadgen] Close broadcast streams only after the workload has completed

### LINKED ISSUE #117: [flaky test] TestLoadGenForOnlyOrderer/block=5,tx=2500
```
      client_test.go:321: 
          	Error Trace:	/home/runner/work/fabric-x-committer/fabric-x-committer/loadgen/client_test.go:375
          	            				/home/runner/work/fabric-x-committer/fabric-x-committer/loadgen/client_test.go:321
          	Error:      	Should be true
          	Test:       	TestLoadGenForOnlyOrderer/block=5,tx=2500
```

### PR DESCRIPTION
**Pull request by liran-funaro**
#### Type of change

- Bug fix
 
#### Description

- Fix bug in load-geneator: Close broadcast streams only after the workload has completed.
This ensures that any pending messages in the stream’s internal queue are fully processed. Even if all transactions have already been submitted, additional time may be required for them to be transmitted.
- Use a connection cache when opening all the connections in the connection manager to avoid re-opening the same connection multiple times.
- Fix broken rebase from prior commit.

#### Related issues

- resolves #117

### CODE REVIEW

File: loadgen/adapters/vcservice.go [hunk 1]
```diff
@@ -78,6 +78,7 @@ func (c *VcAdapter) RunWorkload(ctx context.Context, txStream *workload.StreamWi
 	defer dCancel()
 	g, gCtx := errgroup.WithContext(dCtx)
 	for _, stream := range streams {
+		stream := stream
```
Comment (cendhu) [inline loadgen/adapters/vcservice.go:81]: The loop variable scope has been fixed since go 1.22 -- https://go.dev/blog/loopvar-preview#the-fix
